# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Task_1_1_3
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/gradle-build-action@v2

      - run: chmod +x ./gradlew
      - run: ./gradlew clean build
      - run: ./gradlew jacocoTestReport

      - name: Check coverage and publish
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: Task_1_1_3/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80

      - run: ./gradlew javadoc

      - name: Publish javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: Task_1_1_3/build/docs/javadoc
          target-folder: Task_1_1_3

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: '.github/google_checks.xml'
          reporter: 'github-pr-check'
